float2 sdf(float3 p) {
	outputColor = library.orbitInitInf();
	float4 new_p = float4(p, 1.0f);
	float d = 1e20;
	for (int i = 0; i < library.Iterations; i++) {
		outputColor = library.orbitByType(outputColor, new_p);
		new_p = library.boxFold(new_p, library.FoldSize);
		new_p = library.scaleTranslateFold(new_p, library.FoldingScale, library.Power * library.FoldOffset);
		new_p = library.sphereFold(new_p, 0.5, 1.0f);
		new_p = library.rotYFold(new_p, library.FoldAngles.y);
		new_p = library.absFold(new_p, float3(0.0f, 0.0f, 0.0f));
		new_p = library.rotZFold(new_p, library.FoldAngles.z);
		new_p = library.boxFold(new_p, library.FoldSize);
		outputColor = library.orbitByType(outputColor, new_p);

	}
	return float2(min(d, library.sdBox(new_p, float3(library.Offset, library.Offset, library.Offset))), length(new_p));
}
